### ISSUE TITLE
How are denoising labels generated for a private cryo-electron microscopy image dataset?

### ISSUE THREAD

**Issue by apuomline** [tommyshelby4/MultiCascade-DS-3DUnet#1]
Did the author use a denoising model to generate the denoising labels for the MC DC Net in the SHREC2021 test?

**Comment by apuomline** [comment]
If your denoising labels are generated using a denoising model, could you please tell me about the detailed settings of the denoising parameters? Thank you very much!

> Did the author use a denoising model to generate the denoising labels for the MC DC Net in the SHREC2021 test?

**Comment by StavGer** [comment]
Hi. If I remember correctly, as this contest took place 3 years ago, we were provided with noise-free tomograms which we used as denoising labels. You can find more information about the data (probably even the data themselves) we used in the webpage of the contest.
